title: Hyungbo Shim
description: Professor, Department of Electrical and Computer Engineering, Seoul National University
baseurl: ""
url: "https://hyungbo.github.io"

# Build settings
markdown: kramdown
theme: minima

# Permalinks
permalink: /:title/

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
